### ISSUE TITLE
Followed instructions raspberry PI does not boot

### ISSUE THREAD

**Issue by ptitodd** [pihomeserver/Kupiki-Hotspot#1]
Not sure why, but when I use Mac OS X El Capitan's Drive Utility, I format Micro SD with MS-DOS FAT, copy the files from the .zip and plug into Raspberry PI. It doesn't boot.

Please double check your instructions. As apparently it's not 'as simple' as you make it out be.

**Comment by ptitodd** [comment]
Mac OS X El Capitan+ default Partition table to GUID, partition needs to be in MBR. This might be useful information to include in Read Me

**Comment by pihomeserver** [comment]
Thanks. README updated.
