### ISSUE TITLE
Change wifi Interface

### ISSUE THREAD

**Issue by scottie** [pihomeserver/Kupiki-Hotspot#3]
Fantastic, love this, but how can i change it from using wlan0 (built in wifi on pi3) to using my supported usb wifi dongle for purpose of DBM gain antenna attachment.

**Comment by pihomeserver** [comment]
Hi
Did you try to update the parameter in the script first lines ? You can change the interface name used for lan and wan

**Comment by scottie** [comment]
This is a image the script is the other git ?

**Comment by pihomeserver** [comment]
The latest version is in the repo https://github.com/pihomeserver/Pi-Hotspot-Script

I have ti see how to link from here to the other repo

**Comment by scottie** [comment]
Ok sooo this image is usless??
Also the "script" dosnt work it seems.

**Comment by pihomeserver** [comment]
The script works well and it has been tested by many people. If you have a bug please report it

**Comment by scottie** [comment]
I dont think you understand, this repo IS NOT FOR THE SCRIPT this is a image for a pi OS that contains working install ??? Or area you saying that the image dosnt work and one must go and use the script? As you can see i posted this issue in the repo containing the IMAGE and not the SCRIPT... ??

**Comment by pihomeserver** [comment]
This repo is the net install of latest raspbian with execution of the script once the OS is ready. You should have a minimal install with a hotspot ready
