### ISSUE TITLE
No Wifi

### ISSUE THREAD

**Issue by africanalex** [pihomeserver/Kupiki-Hotspot#6]
I have followed the instructions and logged in to root but when I run ifconfig there is no wlan0?

**Comment by pihomeserver** [comment]
Without real details, it's difficult to help ... log ? model ?

**Comment by africanalex** [comment]
[syslog.txt](https://github.com/pihomeserver/Kupiki-Hotspot/files/860301/syslog.txt)

It is a raspberry pi 3 with onboard wifi, I have it working as an AP under the latest raspbian with PIXEL

**Comment by reigelgallarde** [comment]
please also check `/var/log/pihotspot.log`

**Comment by africanalex** [comment]
**
** Log file created : /var/log/pihotspot.log
** Use command 'tail -f /var/log/pihotspot.log' in a new console to get installation details
** Updating system
Err http://mirrordirector.raspbian.org jessie InRelease

Err http://archive.raspberrypi.org jessie InRelease

Err http://archive.raspberrypi.org jessie Release.gpg
  Could not resolve 'archive.raspberrypi.org'
Err http://mirrordirector.raspbian.org jessie Release.gpg
  Could not resolve 'mirrordirector.raspbian.org'
Reading package lists...
W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie/InRelease

W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/InRelease

W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie/Release.gpg  Could not resolve 'mirrordirector.raspbian.org'

W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/Release.gpg  Could not resolve 'archive.raspberrypi.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
** Upgrading all packages
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be upgraded:
  libpam-modules libpam-modules-bin libpam-runtime libpam0g
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 722 kB of archives.
After this operation, 643 kB disk space will be freed.
WARNING: The following packages cannot be authenticated!
  libpam0g libpam-modules-bin libpam-modules libpam-runtime
E: There are problems and -y was used without --force-yes
**
** Something went wrong with the last command. Please check the log file
**

**Comment by reigelgallarde** [comment]
did you run this without internet? it seems it did not successfully get the things it needed over the internet...  starting here `Err http://mirrordirector.raspbian.org jessie InRelease`

**Comment by africanalex** [comment]
I ran it with internet, not sure why they failed. If I run apt-get update/upgrade will it try to find them?

**Comment by africanalex** [comment]
when I ping google.com I get a response but:
 ping: unknown host http://archive.raspberrypi.org/

**Comment by africanalex** [comment]
I'll try a few things and see if I can get it working, thanks for your help

**Comment by africanalex** [comment]
The issue was when I downloaded the zip of the repo the files in Pi-Hotspot-script directory were missing. A git clone solved this.

**Comment by pihomeserver** [comment]
Strange as the files are in a submodule that needs the -init option. Also the files in this folder are not used because i plan to kill this project and keep going on the script only repo
